jwt:
  token: ${JWT_TOKEN:ac7b9c76236ae1e80f181586a980d292a1a6eb14e3beeaa97d01523ef2a571b1}

report:
  traffic:
    init:
      ttl: 5
    like:
      ttl: 5
    dis-like:
      ttl: 1
  accident:
    init:
      ttl: 10
    like:
      ttl: 10
    dis-like:
      ttl: 5
  police:
    init:
      ttl: 20
    like:
      ttl: 20
    dis-like:
      ttl: 8
  weather:
    init:
      ttl: 60
    like:
      ttl: 50
    dis-like:
      ttl: 20

spring:
  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 40000
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  datasource:
    username: ${DB_USER:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_SCHEMA:traffic}
    password: ${DB_PASS:1376gtid}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'false'
server:
  error:
    include-message: always

logging:
  level:
    org:
      springframework:
        security: DEBUG